### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by tenshiAMD** [generationtux/php-healthz#11]
Greetings~! Requesting to add support for Laravel 8, or I will just create a PR for this one.

**Comment by tenshiAMD** [comment]
@Olofguard please take a look, I hope you could merge this soon so we can use this package with Laravel 8, thanks~! 🎉

**Comment by Olofguard** [comment]
👍 I'll try to prioritize this week.

**Comment by Olofguard** [comment]
v3.1.0 has been published for laravel 8 support. Closing this out.
