### ISSUE TITLE
Support for Laravel 6 or later

### ISSUE THREAD

**Issue by tenshiAMD** [generationtux/php-healthz#8]
any plans on supporting  Laravel 6 or later?

@Olofguard @kyleferguson

**Comment by Olofguard** [comment]
@tenshiAMD yes, though we do not currently have a time frame on this. PRs are welcome though!

**Comment by tenshiAMD** [comment]
@Olofguard okay sure, I will try to create PR regarding this matter.

**Comment by tenshiAMD** [comment]
Closed by https://github.com/generationtux/php-healthz/pull/10.
